package cn.com.jtang.dao;

import cn.com.jtang.po.AccessControl;
import cn.com.jtang.po.AccessControlExample;
import cn.com.jtang.po.AccessControlKey;
import java.util.List;

import cn.com.jtang.resulthandler.AccessResultHandler;
import org.apache.ibatis.annotations.Param;

public interface AccessControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int countByExample(AccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int deleteByExample(AccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int deleteByPrimaryKey(AccessControlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int insert(AccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int insertSelective(AccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    List<AccessControl> selectByExample(AccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    AccessControl selectByPrimaryKey(AccessControlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") AccessControl record, @Param("example") AccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int updateByExample(@Param("record") AccessControl record, @Param("example") AccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int updateByPrimaryKeySelective(AccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    int updateByPrimaryKey(AccessControl record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    void getSelectedAuths(@Param("userid")String userid, AccessResultHandler accessResultHandler);
}