package cn.com.jtang.dao;

import cn.com.jtang.po.AddIndex;
import cn.com.jtang.po.AddIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int countByExample(AddIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int deleteByExample(AddIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int insert(AddIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int insertSelective(AddIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    List<AddIndex> selectByExample(AddIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    AddIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") AddIndex record, @Param("example") AddIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByExample(@Param("record") AddIndex record, @Param("example") AddIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByPrimaryKeySelective(AddIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByPrimaryKey(AddIndex record);
}