package cn.com.jtang.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.com.jtang.po.ArchivesAudit;
import cn.com.jtang.po.ArchivesExample;
import cn.com.jtang.web.controller.form.ArchivesForm;

public interface ArchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int countByExample(ArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int deleteByExample(ArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int insert(ArchivesForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int insertSelective(ArchivesForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    List<ArchivesForm> selectByExample(ArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") ArchivesForm record, @Param("example") ArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int updateByExample(@Param("record") ArchivesForm record, @Param("example") ArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int returnArchives(@Param("id")String id,@Param("returnPerson")String returnPerson);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    List<ArchivesForm> getArchives();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ArchivesForm
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    int isRead(@Param("id")String id);
    
    
    
    
    ArchivesForm getOneArchives(@Param("id")String id);
    
    
    
}