package cn.com.jtang.dao;

import cn.com.jtang.po.DailyBack;
import cn.com.jtang.po.DailyBackExample;
import java.util.List;
import java.util.Map;

import cn.com.jtang.resulthandler.MapResultHandler;
import org.apache.ibatis.annotations.Param;

public interface DailyBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int countByExample(DailyBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int deleteByExample(DailyBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int deleteByPrimaryKey(Integer week);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int insert(DailyBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int insertSelective(DailyBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    List<DailyBack> selectByExample(DailyBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    DailyBack selectByPrimaryKey(Integer week);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") DailyBack record, @Param("example") DailyBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int updateByExample(@Param("record") DailyBack record, @Param("example") DailyBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int updateByPrimaryKeySelective(DailyBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailyback
     *
     * @mbggenerated Wed Sep 21 17:45:15 CST 2016
     */
    int updateByPrimaryKey(DailyBack record);

    void selectDailyMap(MapResultHandler mapResultHandler);

    List<String> selectDailyWeek();

}