package cn.com.jtang.dao;

import cn.com.jtang.po.DefaultExport;
import cn.com.jtang.po.DefaultExportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefaultExportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int countByExample(DefaultExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int deleteByExample(DefaultExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int deleteByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int insert(DefaultExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int insertSelective(DefaultExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    List<DefaultExport> selectByExample(DefaultExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    DefaultExport selectByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") DefaultExport record, @Param("example") DefaultExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int updateByExample(@Param("record") DefaultExport record, @Param("example") DefaultExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int updateByPrimaryKeySelective(DefaultExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defaultexport
     *
     * @mbggenerated Thu Dec 08 16:14:50 CST 2016
     */
    int updateByPrimaryKey(DefaultExport record);
}