package cn.com.jtang.dao;

import cn.com.jtang.po.FullBack;
import cn.com.jtang.po.FullBackExample;
import java.util.List;

import cn.com.jtang.resulthandler.MapResultHandler;
import org.apache.ibatis.annotations.Param;

public interface FullBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int countByExample(FullBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int deleteByExample(FullBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int deleteByPrimaryKey(Integer week);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int insert(FullBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int insertSelective(FullBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    List<FullBack> selectByExample(FullBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    FullBack selectByPrimaryKey(Integer week);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") FullBack record, @Param("example") FullBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int updateByExample(@Param("record") FullBack record, @Param("example") FullBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int updateByPrimaryKeySelective(FullBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    int updateByPrimaryKey(FullBack record);

    void selectFullMap(MapResultHandler mapResultHandler);

    List<String> selectFullWeek();
}