package cn.com.jtang.dao;

import cn.com.jtang.po.IndexTable;
import cn.com.jtang.po.IndexTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int countByExample(IndexTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int deleteByExample(IndexTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int insert(IndexTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int insertSelective(IndexTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    List<IndexTable> selectByExample(IndexTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    IndexTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") IndexTable record, @Param("example") IndexTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByExample(@Param("record") IndexTable record, @Param("example") IndexTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByPrimaryKeySelective(IndexTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    int updateByPrimaryKey(IndexTable record);
}