package cn.com.jtang.dao;

import cn.com.jtang.po.Info;
import cn.com.jtang.po.InfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int countByExample(InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int deleteByExample(InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int insert(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int insertSelective(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    List<Info> selectByExample(InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") Info record, @Param("example") InfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int updateByExample(@Param("record") Info record, @Param("example") InfoExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Jul 14 11:27:20 CST 2016
     */
    int deleteInfoAndTemplateByRecordtypeId( @Param("recordtypeid") String recordtypeid);
}