package cn.com.jtang.dao;

import cn.com.jtang.po.OutputOrder;
import cn.com.jtang.po.OutputOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutputOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    int countByExample(OutputOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    int deleteByExample(OutputOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    int insert(OutputOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    int insertSelective(OutputOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    List<OutputOrder> selectByExample(OutputOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") OutputOrder record, @Param("example") OutputOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputorder
     *
     * @mbggenerated Sat Sep 10 10:28:59 CST 2016
     */
    int updateByExample(@Param("record") OutputOrder record, @Param("example") OutputOrderExample example);
}