package cn.com.jtang.dao;

import cn.com.jtang.po.Pending;
import cn.com.jtang.po.PendingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PendingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int countByExample(PendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int deleteByExample(PendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int insert(Pending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int insertSelective(Pending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    List<Pending> selectByExample(PendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    Pending selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") Pending record, @Param("example") PendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int updateByExample(@Param("record") Pending record, @Param("example") PendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int updateByPrimaryKeySelective(Pending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending
     *
     * @mbggenerated Wed Jul 06 16:06:21 CST 2016
     */
    int updateByPrimaryKey(Pending record);
}