package cn.com.jtang.dao;

import cn.com.jtang.po.RecordCategory;
import cn.com.jtang.po.RecordCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int countByExample(RecordCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int deleteByExample(RecordCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int insert(RecordCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int insertSelective(RecordCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    List<RecordCategory> selectByExample(RecordCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    RecordCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") RecordCategory record, @Param("example") RecordCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int updateByExample(@Param("record") RecordCategory record, @Param("example") RecordCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int updateByPrimaryKeySelective(RecordCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    int updateByPrimaryKey(RecordCategory record);
}