package cn.com.jtang.dao;

import cn.com.jtang.po.RecordVolume;
import cn.com.jtang.po.RecordVolumeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordVolumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int countByExample(RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int deleteByExample(RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int insert(RecordVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int insertSelective(RecordVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    List<RecordVolume> selectByExample(RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    RecordVolume selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") RecordVolume record, @Param("example") RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int updateByExample(@Param("record") RecordVolume record, @Param("example") RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int updateByPrimaryKeySelective(RecordVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    int updateByPrimaryKey(RecordVolume record);

    List<String> selectIdsByExample (RecordVolumeExample example);
}