package cn.com.jtang.dao;

import cn.com.jtang.po.Record;
import cn.com.jtang.po.RecordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int countByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int deleteByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    List<Record> selectByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    Record selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    int updateByPrimaryKey(Record record);

    Map<String,String> selectFields (@Param("recordId") String recordId, @Param("fields") List<String> fields, @Param("tableName") String tableName);

    List<String> selectIdsByExample (RecordExample example);
    
    int delete (@Param("recordid") String recordid, @Param("tableName") String tableName);
}