package cn.com.jtang.dao;

import cn.com.jtang.po.CreateTable;
import cn.com.jtang.po.RecordType;
import cn.com.jtang.po.RecordTypeExample;
import cn.com.jtang.po.TableField;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecordTypeBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int countByExample(RecordTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int deleteByExample(RecordTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int insert(RecordType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int insertSelective(RecordType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    List<RecordType> selectByExample(RecordTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    RecordType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") RecordType record, @Param("example") RecordTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int updateByExample(@Param("record") RecordType record, @Param("example") RecordTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int updateByPrimaryKeySelective(RecordType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    int updateByPrimaryKey(RecordType record);
    
    
    

    int createRecordTable(CreateTable record);
    
    
    
    int createVolumeTable(CreateTable record);
    
    
    
    int createDocumentTable(CreateTable record);
    
    
    
    int createPieceTable(CreateTable record);
    
    

    int createPieceDocumentTable(CreateTable record);
    
    

    int insertFields(TableField tableField);
    

    
    List<TableField> getFields(@Param("recordtypeid") String recordtypeid, @Param("type") String type);
    
    
    List<TableField> getAllFields(@Param("recordtypeid") String recordtypeid, @Param("type") String type);
    
    

    /*List<Table> selectTableByRecordTypeId(String recordtypeid);*/
}