package cn.com.jtang.dao;

import cn.com.jtang.po.Year;
import cn.com.jtang.po.YearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int countByExample(YearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int deleteByExample(YearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int insert(Year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int insertSelective(Year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    List<Year> selectByExample(YearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    Year selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") Year record, @Param("example") YearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int updateByExample(@Param("record") Year record, @Param("example") YearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int updateByPrimaryKeySelective(Year record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year
     *
     * @mbggenerated Wed Jul 06 19:05:07 CST 2016
     */
    int updateByPrimaryKey(Year record);
}