package cn.com.jtang.dao.custom;

import cn.com.jtang.po.RecordVolume;
import cn.com.jtang.po.RecordVolumeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RecordVolumeViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int countByExample(RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int deleteByExample(RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int insert(@Param("record") RecordVolume record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int insertSelective(@Param("record") RecordVolume record, @Param("tableName") String tableName,@Param("customKeys") List<String> keys,@Param("customValues") List<String> values);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    List<RecordVolume> selectByExample(RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    RecordVolume selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") RecordVolume record, @Param("example") RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByExample(@Param("record") RecordVolume record, @Param("example") RecordVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByPrimaryKeySelective(@Param("record") RecordVolume record, @Param("tableName") String tableName, @Param("keys")List<String> keys, @Param("vmap")Map<String,String> vmap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByPrimaryKey(RecordVolume record);

    List<RecordVolume> selectExportByExample(RecordVolumeExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    String getVolumeidByVolumeNo(@Param("volumeNo")String volumeNo,@Param("tableName")String tableName);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int deleteVolumeByNo(@Param("volumeno")String volumeno,@Param("tableprefix")String tableprefix);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int deleteRecordByNo(@Param("recordno")String recordno,@Param("tablename")String tablename,@Param("documenttable")String documenttable);
}