package cn.com.jtang.dao.custom;

import cn.com.jtang.po.Condition;
import cn.com.jtang.po.Record;
import cn.com.jtang.po.RecordExample;
import cn.com.jtang.po.SelectImformation;
import cn.com.jtang.po.custom.RecordView;
import cn.com.jtang.po.custom.RecordViewExample;

import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RecordViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int countByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int deleteByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int insert(@Param("record") Record record, @Param("tableName") String tableName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int insertByFieldNameAndValue(@Param("fieldname")List<String> fieldname,@Param("fieldvalue")List<String> fieldvalue,@Param("tablename")String tablename
    		,@Param("id")String id,@Param("username")String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int insertSelective(@Param("record") Record record, @Param("tableName") String tableName, @Param("customKeys") List<String> keys,@Param("customValues") List<String> values);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    List<Record> selectByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    Record selectByPrimaryKey(@Param("id") String id, @Param("tableName") String tableName);

    RecordView selectViewByPrimaryKey(@Param("id") String id, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByExampleSelective2(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByPrimaryKeySelective(@Param("record") Record record, @Param("tableName") String tableName, @Param("keys") List<String> keys,@Param("values") Map<String, String> values);

    int updateByPrimaryKeySelectiveCustom(@Param("record") Record record, @Param("customFields") Map<String, String> customFields, @Param("keys")  List<String> keys);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int updateByPrimaryKey(@Param("record") Record record, @Param("tableName") String tableName);


    List<Record> getApplyRecord(@Param("example") RecordViewExample example, @Param("tablename") String tablename);


    int getApplyRecordCount(@Param("example") RecordViewExample example, @Param("tablename") String tablename);


    Map<String, Object> getImformation(SelectImformation record);


    Map<String, Object> getAllById(SelectImformation record);

    
    Map<String, Object> getRecordNoMapData(SelectImformation record);


    Map<String,Object> selectRecordMapByRecordId(@Param("tablename") String tablename, @Param("recordid") String recordid);
    

    int checkPass(@Param("tablename") String tablename, @Param("recordid") String recordid, @Param("recordno") String recordno,
    					@Param("sequencNo") String sequencNo,@Param("checkstatus") String checkstatus);


    int refusePass(@Param("tablename") String tablename, @Param("recordid") String recordid, @Param("checkstatus") String checkstatus);
    

    int CheckInfoCount( @Param("recordid") String recordid);
    

    int updateCheckInfo(@Param("recordid") String recordid,@Param("failReason") String failReason);
    
    
    int insertCheckInfo(@Param("tablename") String tablename, @Param("recordid") String recordid,@Param("failReason") String failReason);

    int countAll(@Param("tablename") String tablename);
    
    String getFailReason(@Param("recordid") String recordid);
    
    int selectRecordCountsByContent(Map map);
    
    List<String> selectRecordidsByContent(Map map);

    List<Map<String,Object>> selectVolumeByContent(Map map);
    
    int selectVolumeCountByContent(Map map);
    
    String selectVolumeSubjectByVolumeId(Map map);
    
    String selectVolumeNoByVolumeId(Map map);
    
    List<Map<String,Object>> selectRecordByVolumeId(Map map);
    
    int deleteCheckInfoByRecordTypeId(@Param("tablenames")List<String> tablenames);
    
    int getSequencNo(@Param("tablename")String tablename,@Param("condition")List<Condition> condition);
    
    int getIndexByValue(@Param("tablename")String tablename,@Param("value")String value);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Wed Jun 22 14:18:55 CST 2016
     */
    int selectCountByExample(RecordExample example);
    
    List<Map<String,Object>> selectAllByExample(RecordExample example);
    

    List<Record> getByVolumeNo(Map map);

    
    int selectPiecesCountByContent(Map map);

    
    List<Map> selectPiecesByContent(Map map);
    
}