package cn.com.jtang.dao.custom;

import cn.com.jtang.po.Authority;
import cn.com.jtang.po.UserGroupAuthExample;
import cn.com.jtang.po.UserGroupAuthKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserGroupAuthViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int countByExample(UserGroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int deleteByExample(UserGroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int deleteByPrimaryKey(UserGroupAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int insert(UserGroupAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int insertSelective(UserGroupAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    List<UserGroupAuthKey> selectByExample(UserGroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserGroupAuthKey record, @Param("example") UserGroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    int updateByExample(@Param("record") UserGroupAuthKey record, @Param("example") UserGroupAuthExample example);

    List<Authority> selectAuthByUserGroup(@Param("usergroupid") String usergroupid);
}