package cn.com.jtang.po;

import java.io.Serializable;

public class AccessControl extends AccessControlKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesscontrol.accesspermission
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    private String accesspermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesscontrol
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesscontrol.accesspermission
     *
     * @return the value of accesscontrol.accesspermission
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    public String getAccesspermission() {
        return accesspermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesscontrol.accesspermission
     *
     * @param accesspermission the value for accesscontrol.accesspermission
     *
     * @mbggenerated Sat Sep 10 15:37:00 CST 2016
     */
    public void setAccesspermission(String accesspermission) {
        this.accesspermission = accesspermission;
    }
}