package cn.com.jtang.po;

import java.io.Serializable;

public class Category implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.categoryname
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.categoryname
     *
     * @return the value of category.categoryname
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.categoryname
     *
     * @param categoryname the value for category.categoryname
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }
}