package cn.com.jtang.po;

import java.io.Serializable;
import java.util.Date;

public class CategoryContent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorycontent.id
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorycontent.categoryNo
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private String categoryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorycontent.value
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorycontent.createtime
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categorycontent.updatetime
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table categorycontent
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorycontent.id
     *
     * @return the value of categorycontent.id
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorycontent.id
     *
     * @param id the value for categorycontent.id
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorycontent.categoryNo
     *
     * @return the value of categorycontent.categoryNo
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public String getCategoryno() {
        return categoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorycontent.categoryNo
     *
     * @param categoryno the value for categorycontent.categoryNo
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setCategoryno(String categoryno) {
        this.categoryno = categoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorycontent.value
     *
     * @return the value of categorycontent.value
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorycontent.value
     *
     * @param value the value for categorycontent.value
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorycontent.createtime
     *
     * @return the value of categorycontent.createtime
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorycontent.createtime
     *
     * @param createtime the value for categorycontent.createtime
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categorycontent.updatetime
     *
     * @return the value of categorycontent.updatetime
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categorycontent.updatetime
     *
     * @param updatetime the value for categorycontent.updatetime
     *
     * @mbggenerated Thu Jun 30 17:47:12 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}