package cn.com.jtang.po;

import java.io.Serializable;

public class FullBack implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fullback.week
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fullback.cronexpression
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    private String cronexpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fullback
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fullback.week
     *
     * @return the value of fullback.week
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fullback.week
     *
     * @param week the value for fullback.week
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fullback.cronexpression
     *
     * @return the value of fullback.cronexpression
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    public String getCronexpression() {
        return cronexpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fullback.cronexpression
     *
     * @param cronexpression the value for fullback.cronexpression
     *
     * @mbggenerated Thu Sep 22 11:43:58 CST 2016
     */
    public void setCronexpression(String cronexpression) {
        this.cronexpression = cronexpression;
    }
}