package cn.com.jtang.po;

import java.io.Serializable;

public class IndexTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indextable.id
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indextable.indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    private String indextable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indextable.name
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indextable.id
     *
     * @return the value of indextable.id
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indextable.id
     *
     * @param id the value for indextable.id
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indextable.indextable
     *
     * @return the value of indextable.indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    public String getIndextable() {
        return indextable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indextable.indextable
     *
     * @param indextable the value for indextable.indextable
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    public void setIndextable(String indextable) {
        this.indextable = indextable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indextable.name
     *
     * @return the value of indextable.name
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indextable.name
     *
     * @param name the value for indextable.name
     *
     * @mbggenerated Thu Aug 11 10:21:34 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}