package cn.com.jtang.po;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.event
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operator
     *
     * @return the value of log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operator
     *
     * @param operator the value for log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.event
     *
     * @return the value of log.event
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.event
     *
     * @param event the value for log.event
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public void setEvent(String event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.createtime
     *
     * @return the value of log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.createtime
     *
     * @param createtime the value for log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}