package cn.com.jtang.po;

import java.io.Serializable;
import java.util.Date;

public class Record implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.id
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.subject
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.recordNo
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String recordno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.sequencNo
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String sequencno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.volumeid
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String volumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.tableid
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String tableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.deadline
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.department
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.year
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.description
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.pagenum
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer pagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.checkstatus
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.operator
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.address
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.people
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.createtime
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.updatetime
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cstr1
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String cstr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cstr2
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String cstr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cstr3
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String cstr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cstr4
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String cstr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cstr5
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private String cstr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cint1
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer cint1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cint2
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer cint2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cint3
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer cint3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cint4
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer cint4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f1_w1_record.cint5
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private Integer cint5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f1_w1_record
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.id
     *
     * @return the value of f1_w1_record.id
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.id
     *
     * @param id the value for f1_w1_record.id
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.subject
     *
     * @return the value of f1_w1_record.subject
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.subject
     *
     * @param subject the value for f1_w1_record.subject
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.recordNo
     *
     * @return the value of f1_w1_record.recordNo
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getRecordno() {
        return recordno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.recordNo
     *
     * @param recordno the value for f1_w1_record.recordNo
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setRecordno(String recordno) {
        this.recordno = recordno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.sequencNo
     *
     * @return the value of f1_w1_record.sequencNo
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getSequencno() {
        return sequencno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.sequencNo
     *
     * @param sequencno the value for f1_w1_record.sequencNo
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setSequencno(String sequencno) {
        this.sequencno = sequencno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.volumeid
     *
     * @return the value of f1_w1_record.volumeid
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getVolumeid() {
        return volumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.volumeid
     *
     * @param volumeid the value for f1_w1_record.volumeid
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setVolumeid(String volumeid) {
        this.volumeid = volumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.tableid
     *
     * @return the value of f1_w1_record.tableid
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.tableid
     *
     * @param tableid the value for f1_w1_record.tableid
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.deadline
     *
     * @return the value of f1_w1_record.deadline
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.deadline
     *
     * @param deadline the value for f1_w1_record.deadline
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setDeadline(Integer deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.department
     *
     * @return the value of f1_w1_record.department
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.department
     *
     * @param department the value for f1_w1_record.department
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.year
     *
     * @return the value of f1_w1_record.year
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.year
     *
     * @param year the value for f1_w1_record.year
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.description
     *
     * @return the value of f1_w1_record.description
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.description
     *
     * @param description the value for f1_w1_record.description
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.pagenum
     *
     * @return the value of f1_w1_record.pagenum
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getPagenum() {
        return pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.pagenum
     *
     * @param pagenum the value for f1_w1_record.pagenum
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setPagenum(Integer pagenum) {
        this.pagenum = pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.checkstatus
     *
     * @return the value of f1_w1_record.checkstatus
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.checkstatus
     *
     * @param checkstatus the value for f1_w1_record.checkstatus
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCheckstatus(String checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.operator
     *
     * @return the value of f1_w1_record.operator
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.operator
     *
     * @param operator the value for f1_w1_record.operator
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.address
     *
     * @return the value of f1_w1_record.address
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.address
     *
     * @param address the value for f1_w1_record.address
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.people
     *
     * @return the value of f1_w1_record.people
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.people
     *
     * @param people the value for f1_w1_record.people
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setPeople(String people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.createtime
     *
     * @return the value of f1_w1_record.createtime
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.createtime
     *
     * @param createtime the value for f1_w1_record.createtime
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.updatetime
     *
     * @return the value of f1_w1_record.updatetime
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.updatetime
     *
     * @param updatetime the value for f1_w1_record.updatetime
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cstr1
     *
     * @return the value of f1_w1_record.cstr1
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getCstr1() {
        return cstr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cstr1
     *
     * @param cstr1 the value for f1_w1_record.cstr1
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCstr1(String cstr1) {
        this.cstr1 = cstr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cstr2
     *
     * @return the value of f1_w1_record.cstr2
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getCstr2() {
        return cstr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cstr2
     *
     * @param cstr2 the value for f1_w1_record.cstr2
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCstr2(String cstr2) {
        this.cstr2 = cstr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cstr3
     *
     * @return the value of f1_w1_record.cstr3
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getCstr3() {
        return cstr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cstr3
     *
     * @param cstr3 the value for f1_w1_record.cstr3
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCstr3(String cstr3) {
        this.cstr3 = cstr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cstr4
     *
     * @return the value of f1_w1_record.cstr4
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getCstr4() {
        return cstr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cstr4
     *
     * @param cstr4 the value for f1_w1_record.cstr4
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCstr4(String cstr4) {
        this.cstr4 = cstr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cstr5
     *
     * @return the value of f1_w1_record.cstr5
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public String getCstr5() {
        return cstr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cstr5
     *
     * @param cstr5 the value for f1_w1_record.cstr5
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCstr5(String cstr5) {
        this.cstr5 = cstr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cint1
     *
     * @return the value of f1_w1_record.cint1
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getCint1() {
        return cint1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cint1
     *
     * @param cint1 the value for f1_w1_record.cint1
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCint1(Integer cint1) {
        this.cint1 = cint1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cint2
     *
     * @return the value of f1_w1_record.cint2
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getCint2() {
        return cint2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cint2
     *
     * @param cint2 the value for f1_w1_record.cint2
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCint2(Integer cint2) {
        this.cint2 = cint2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cint3
     *
     * @return the value of f1_w1_record.cint3
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getCint3() {
        return cint3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cint3
     *
     * @param cint3 the value for f1_w1_record.cint3
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCint3(Integer cint3) {
        this.cint3 = cint3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cint4
     *
     * @return the value of f1_w1_record.cint4
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getCint4() {
        return cint4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cint4
     *
     * @param cint4 the value for f1_w1_record.cint4
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCint4(Integer cint4) {
        this.cint4 = cint4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f1_w1_record.cint5
     *
     * @return the value of f1_w1_record.cint5
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public Integer getCint5() {
        return cint5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f1_w1_record.cint5
     *
     * @param cint5 the value for f1_w1_record.cint5
     *
     * @mbggenerated Tue Jul 19 15:58:50 CST 2016
     */
    public void setCint5(Integer cint5) {
        this.cint5 = cint5;
    }
}