package cn.com.jtang.po;

import java.io.Serializable;
import java.util.Date;

public class RecordCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordcategory.id
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordcategory.des
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordcategory.createtime
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recordcategory
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordcategory.id
     *
     * @return the value of recordcategory.id
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordcategory.id
     *
     * @param id the value for recordcategory.id
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordcategory.des
     *
     * @return the value of recordcategory.des
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordcategory.des
     *
     * @param des the value for recordcategory.des
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordcategory.createtime
     *
     * @return the value of recordcategory.createtime
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordcategory.createtime
     *
     * @param createtime the value for recordcategory.createtime
     *
     * @mbggenerated Tue Jun 21 17:09:18 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}