package cn.com.jtang.po;

import cn.com.jtang.po.custom.Table;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class RecordTypeBack implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.id
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.fondsid
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private String fondsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.name
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.volumetable
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private String volumetable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.recordtable
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private String recordtable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.typeNo
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private String typeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordtype.createtime
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recordtype
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */

    private List<Table> tables;
    
    
    
    
    public List<Table> getTables() {
		return tables;
	}

	public void setTables(List<Table> tables) {
		this.tables = tables;
	}



	private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.id
     *
     * @return the value of recordtype.id
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.id
     *
     * @param id the value for recordtype.id
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.fondsid
     *
     * @return the value of recordtype.fondsid
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public String getFondsid() {
        return fondsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.fondsid
     *
     * @param fondsid the value for recordtype.fondsid
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setFondsid(String fondsid) {
        this.fondsid = fondsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.name
     *
     * @return the value of recordtype.name
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.name
     *
     * @param name the value for recordtype.name
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.volumetable
     *
     * @return the value of recordtype.volumetable
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public String getVolumetable() {
        return volumetable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.volumetable
     *
     * @param volumetable the value for recordtype.volumetable
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setVolumetable(String volumetable) {
        this.volumetable = volumetable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.recordtable
     *
     * @return the value of recordtype.recordtable
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public String getRecordtable() {
        return recordtable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.recordtable
     *
     * @param recordtable the value for recordtype.recordtable
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setRecordtable(String recordtable) {
        this.recordtable = recordtable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.typeNo
     *
     * @return the value of recordtype.typeNo
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public String getTypeno() {
        return typeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.typeNo
     *
     * @param typeno the value for recordtype.typeNo
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setTypeno(String typeno) {
        this.typeno = typeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordtype.createtime
     *
     * @return the value of recordtype.createtime
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordtype.createtime
     *
     * @param createtime the value for recordtype.createtime
     *
     * @mbggenerated Thu Jun 30 14:06:51 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    



}