package cn.com.jtang.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import cn.com.jtang.po.RecordExample.Criteria;
import cn.com.jtang.web.controller.form.template.Column;

public class RecordVolumeExample {
    protected String tableName;

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public RecordVolumeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andVolumenoIsNull() {
            addCriterion("volumeNo is null");
            return (Criteria) this;
        }

        public Criteria andVolumenoIsNotNull() {
            addCriterion("volumeNo is not null");
            return (Criteria) this;
        }

        public Criteria andVolumenoEqualTo(String value) {
            addCriterion("volumeNo =", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoNotEqualTo(String value) {
            addCriterion("volumeNo <>", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoGreaterThan(String value) {
            addCriterion("volumeNo >", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoGreaterThanOrEqualTo(String value) {
            addCriterion("volumeNo >=", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoLessThan(String value) {
            addCriterion("volumeNo <", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoLessThanOrEqualTo(String value) {
            addCriterion("volumeNo <=", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoLike(String value) {
            addCriterion("volumeNo like", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoNotLike(String value) {
            addCriterion("volumeNo not like", value, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoIn(List<String> values) {
            addCriterion("volumeNo in", values, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoNotIn(List<String> values) {
            addCriterion("volumeNo not in", values, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoBetween(String value1, String value2) {
            addCriterion("volumeNo between", value1, value2, "volumeno");
            return (Criteria) this;
        }

        public Criteria andVolumenoNotBetween(String value1, String value2) {
            addCriterion("volumeNo not between", value1, value2, "volumeno");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineEqualTo(Integer value) {
            addCriterion("deadline =", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotEqualTo(Integer value) {
            addCriterion("deadline <>", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThan(Integer value) {
            addCriterion("deadline >", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(Integer value) {
            addCriterion("deadline >=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThan(Integer value) {
            addCriterion("deadline <", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(Integer value) {
            addCriterion("deadline <=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineIn(List<Integer> values) {
            addCriterion("deadline in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotIn(List<Integer> values) {
            addCriterion("deadline not in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineBetween(Integer value1, Integer value2) {
            addCriterion("deadline between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotBetween(Integer value1, Integer value2) {
            addCriterion("deadline not between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(Integer value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(Integer value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(Integer value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(Integer value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(Integer value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<Integer> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<Integer> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(Integer value1, Integer value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(Integer value1, Integer value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andOneEqualTo(String field, String value) {
            addCriterion(field+" =", value, field);
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andCheckstatusIsNull() {
            addCriterion("checkstatus is null");
            return (Criteria) this;
        }

        public Criteria andCheckstatusIsNotNull() {
            addCriterion("checkstatus is not null");
            return (Criteria) this;
        }

        public Criteria andCheckstatusEqualTo(String value) {
            addCriterion("checkstatus =", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotEqualTo(String value) {
            addCriterion("checkstatus <>", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusGreaterThan(String value) {
            addCriterion("checkstatus >", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusGreaterThanOrEqualTo(String value) {
            addCriterion("checkstatus >=", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusLessThan(String value) {
            addCriterion("checkstatus <", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusLessThanOrEqualTo(String value) {
            addCriterion("checkstatus <=", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusLike(String value) {
            addCriterion("checkstatus like", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotLike(String value) {
            addCriterion("checkstatus not like", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusIn(List<String> values) {
            addCriterion("checkstatus in", values, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotIn(List<String> values) {
            addCriterion("checkstatus not in", values, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusBetween(String value1, String value2) {
            addCriterion("checkstatus between", value1, value2, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotBetween(String value1, String value2) {
            addCriterion("checkstatus not between", value1, value2, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andInnersizeIsNull() {
            addCriterion("innersize is null");
            return (Criteria) this;
        }

        public Criteria andInnersizeIsNotNull() {
            addCriterion("innersize is not null");
            return (Criteria) this;
        }

        public Criteria andInnersizeEqualTo(Integer value) {
            addCriterion("innersize =", value, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeNotEqualTo(Integer value) {
            addCriterion("innersize <>", value, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeGreaterThan(Integer value) {
            addCriterion("innersize >", value, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("innersize >=", value, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeLessThan(Integer value) {
            addCriterion("innersize <", value, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeLessThanOrEqualTo(Integer value) {
            addCriterion("innersize <=", value, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeIn(List<Integer> values) {
            addCriterion("innersize in", values, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeNotIn(List<Integer> values) {
            addCriterion("innersize not in", values, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeBetween(Integer value1, Integer value2) {
            addCriterion("innersize between", value1, value2, "innersize");
            return (Criteria) this;
        }

        public Criteria andInnersizeNotBetween(Integer value1, Integer value2) {
            addCriterion("innersize not between", value1, value2, "innersize");
            return (Criteria) this;
        }

        public Criteria andPagenumIsNull() {
            addCriterion("pagenum is null");
            return (Criteria) this;
        }

        public Criteria andPagenumIsNotNull() {
            addCriterion("pagenum is not null");
            return (Criteria) this;
        }

        public Criteria andPagenumEqualTo(Integer value) {
            addCriterion("pagenum =", value, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumNotEqualTo(Integer value) {
            addCriterion("pagenum <>", value, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumGreaterThan(Integer value) {
            addCriterion("pagenum >", value, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("pagenum >=", value, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumLessThan(Integer value) {
            addCriterion("pagenum <", value, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumLessThanOrEqualTo(Integer value) {
            addCriterion("pagenum <=", value, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumIn(List<Integer> values) {
            addCriterion("pagenum in", values, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumNotIn(List<Integer> values) {
            addCriterion("pagenum not in", values, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumBetween(Integer value1, Integer value2) {
            addCriterion("pagenum between", value1, value2, "pagenum");
            return (Criteria) this;
        }

        public Criteria andPagenumNotBetween(Integer value1, Integer value2) {
            addCriterion("pagenum not between", value1, value2, "pagenum");
            return (Criteria) this;
        }

        public Criteria andTimerangeIsNull() {
            addCriterion("timerange is null");
            return (Criteria) this;
        }

        public Criteria andTimerangeIsNotNull() {
            addCriterion("timerange is not null");
            return (Criteria) this;
        }

        public Criteria andTimerangeEqualTo(String value) {
            addCriterion("timerange =", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeNotEqualTo(String value) {
            addCriterion("timerange <>", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeGreaterThan(String value) {
            addCriterion("timerange >", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeGreaterThanOrEqualTo(String value) {
            addCriterion("timerange >=", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeLessThan(String value) {
            addCriterion("timerange <", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeLessThanOrEqualTo(String value) {
            addCriterion("timerange <=", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeLike(String value) {
            addCriterion("timerange like", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeNotLike(String value) {
            addCriterion("timerange not like", value, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeIn(List<String> values) {
            addCriterion("timerange in", values, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeNotIn(List<String> values) {
            addCriterion("timerange not in", values, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeBetween(String value1, String value2) {
            addCriterion("timerange between", value1, value2, "timerange");
            return (Criteria) this;
        }

        public Criteria andTimerangeNotBetween(String value1, String value2) {
            addCriterion("timerange not between", value1, value2, "timerange");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andPeopleIsNull() {
            addCriterion("people is null");
            return (Criteria) this;
        }

        public Criteria andPeopleIsNotNull() {
            addCriterion("people is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleEqualTo(String value) {
            addCriterion("people =", value, "people");
            return (Criteria) this;
        }

        public Criteria andLIkeByCol(List<Column> cols) {
        	for(Column col:cols){
        		if(col.getColvalue()!=null&&!col.getColvalue().equals(""))
        			addCriterion(col.getColid()+" like ","%"+col.getColvalue()+"%", col.getColid());
        	}
            return (Criteria) this;
        }
        public Criteria andPeopleNotEqualTo(String value) {
            addCriterion("people <>", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleGreaterThan(String value) {
            addCriterion("people >", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("people >=", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLessThan(String value) {
            addCriterion("people <", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLessThanOrEqualTo(String value) {
            addCriterion("people <=", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLike(String value) {
            addCriterion("people like", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotLike(String value) {
            addCriterion("people not like", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleIn(List<String> values) {
            addCriterion("people in", values, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotIn(List<String> values) {
            addCriterion("people not in", values, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleBetween(String value1, String value2) {
            addCriterion("people between", value1, value2, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotBetween(String value1, String value2) {
            addCriterion("people not between", value1, value2, "people");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andCstr1IsNull() {
            addCriterion("cstr1 is null");
            return (Criteria) this;
        }

        public Criteria andCstr1IsNotNull() {
            addCriterion("cstr1 is not null");
            return (Criteria) this;
        }

        public Criteria andCstr1EqualTo(String value) {
            addCriterion("cstr1 =", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1NotEqualTo(String value) {
            addCriterion("cstr1 <>", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1GreaterThan(String value) {
            addCriterion("cstr1 >", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1GreaterThanOrEqualTo(String value) {
            addCriterion("cstr1 >=", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1LessThan(String value) {
            addCriterion("cstr1 <", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1LessThanOrEqualTo(String value) {
            addCriterion("cstr1 <=", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1Like(String value) {
            addCriterion("cstr1 like", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1NotLike(String value) {
            addCriterion("cstr1 not like", value, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1In(List<String> values) {
            addCriterion("cstr1 in", values, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1NotIn(List<String> values) {
            addCriterion("cstr1 not in", values, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1Between(String value1, String value2) {
            addCriterion("cstr1 between", value1, value2, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr1NotBetween(String value1, String value2) {
            addCriterion("cstr1 not between", value1, value2, "cstr1");
            return (Criteria) this;
        }

        public Criteria andCstr2IsNull() {
            addCriterion("cstr2 is null");
            return (Criteria) this;
        }

        public Criteria andCstr2IsNotNull() {
            addCriterion("cstr2 is not null");
            return (Criteria) this;
        }

        public Criteria andCstr2EqualTo(String value) {
            addCriterion("cstr2 =", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2NotEqualTo(String value) {
            addCriterion("cstr2 <>", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2GreaterThan(String value) {
            addCriterion("cstr2 >", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2GreaterThanOrEqualTo(String value) {
            addCriterion("cstr2 >=", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2LessThan(String value) {
            addCriterion("cstr2 <", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2LessThanOrEqualTo(String value) {
            addCriterion("cstr2 <=", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2Like(String value) {
            addCriterion("cstr2 like", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2NotLike(String value) {
            addCriterion("cstr2 not like", value, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2In(List<String> values) {
            addCriterion("cstr2 in", values, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2NotIn(List<String> values) {
            addCriterion("cstr2 not in", values, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2Between(String value1, String value2) {
            addCriterion("cstr2 between", value1, value2, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr2NotBetween(String value1, String value2) {
            addCriterion("cstr2 not between", value1, value2, "cstr2");
            return (Criteria) this;
        }

        public Criteria andCstr3IsNull() {
            addCriterion("cstr3 is null");
            return (Criteria) this;
        }

        public Criteria andCstr3IsNotNull() {
            addCriterion("cstr3 is not null");
            return (Criteria) this;
        }

        public Criteria andCstr3EqualTo(String value) {
            addCriterion("cstr3 =", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3NotEqualTo(String value) {
            addCriterion("cstr3 <>", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3GreaterThan(String value) {
            addCriterion("cstr3 >", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3GreaterThanOrEqualTo(String value) {
            addCriterion("cstr3 >=", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3LessThan(String value) {
            addCriterion("cstr3 <", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3LessThanOrEqualTo(String value) {
            addCriterion("cstr3 <=", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3Like(String value) {
            addCriterion("cstr3 like", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3NotLike(String value) {
            addCriterion("cstr3 not like", value, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3In(List<String> values) {
            addCriterion("cstr3 in", values, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3NotIn(List<String> values) {
            addCriterion("cstr3 not in", values, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3Between(String value1, String value2) {
            addCriterion("cstr3 between", value1, value2, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr3NotBetween(String value1, String value2) {
            addCriterion("cstr3 not between", value1, value2, "cstr3");
            return (Criteria) this;
        }

        public Criteria andCstr4IsNull() {
            addCriterion("cstr4 is null");
            return (Criteria) this;
        }

        public Criteria andCstr4IsNotNull() {
            addCriterion("cstr4 is not null");
            return (Criteria) this;
        }

        public Criteria andCstr4EqualTo(String value) {
            addCriterion("cstr4 =", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4NotEqualTo(String value) {
            addCriterion("cstr4 <>", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4GreaterThan(String value) {
            addCriterion("cstr4 >", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4GreaterThanOrEqualTo(String value) {
            addCriterion("cstr4 >=", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4LessThan(String value) {
            addCriterion("cstr4 <", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4LessThanOrEqualTo(String value) {
            addCriterion("cstr4 <=", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4Like(String value) {
            addCriterion("cstr4 like", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4NotLike(String value) {
            addCriterion("cstr4 not like", value, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4In(List<String> values) {
            addCriterion("cstr4 in", values, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4NotIn(List<String> values) {
            addCriterion("cstr4 not in", values, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4Between(String value1, String value2) {
            addCriterion("cstr4 between", value1, value2, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr4NotBetween(String value1, String value2) {
            addCriterion("cstr4 not between", value1, value2, "cstr4");
            return (Criteria) this;
        }

        public Criteria andCstr5IsNull() {
            addCriterion("cstr5 is null");
            return (Criteria) this;
        }

        public Criteria andCstr5IsNotNull() {
            addCriterion("cstr5 is not null");
            return (Criteria) this;
        }

        public Criteria andCstr5EqualTo(String value) {
            addCriterion("cstr5 =", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5NotEqualTo(String value) {
            addCriterion("cstr5 <>", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5GreaterThan(String value) {
            addCriterion("cstr5 >", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5GreaterThanOrEqualTo(String value) {
            addCriterion("cstr5 >=", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5LessThan(String value) {
            addCriterion("cstr5 <", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5LessThanOrEqualTo(String value) {
            addCriterion("cstr5 <=", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5Like(String value) {
            addCriterion("cstr5 like", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5NotLike(String value) {
            addCriterion("cstr5 not like", value, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5In(List<String> values) {
            addCriterion("cstr5 in", values, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5NotIn(List<String> values) {
            addCriterion("cstr5 not in", values, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5Between(String value1, String value2) {
            addCriterion("cstr5 between", value1, value2, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCstr5NotBetween(String value1, String value2) {
            addCriterion("cstr5 not between", value1, value2, "cstr5");
            return (Criteria) this;
        }

        public Criteria andCint1IsNull() {
            addCriterion("cint1 is null");
            return (Criteria) this;
        }

        public Criteria andCint1IsNotNull() {
            addCriterion("cint1 is not null");
            return (Criteria) this;
        }

        public Criteria andCint1EqualTo(Integer value) {
            addCriterion("cint1 =", value, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1NotEqualTo(Integer value) {
            addCriterion("cint1 <>", value, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1GreaterThan(Integer value) {
            addCriterion("cint1 >", value, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1GreaterThanOrEqualTo(Integer value) {
            addCriterion("cint1 >=", value, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1LessThan(Integer value) {
            addCriterion("cint1 <", value, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1LessThanOrEqualTo(Integer value) {
            addCriterion("cint1 <=", value, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1In(List<Integer> values) {
            addCriterion("cint1 in", values, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1NotIn(List<Integer> values) {
            addCriterion("cint1 not in", values, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1Between(Integer value1, Integer value2) {
            addCriterion("cint1 between", value1, value2, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint1NotBetween(Integer value1, Integer value2) {
            addCriterion("cint1 not between", value1, value2, "cint1");
            return (Criteria) this;
        }

        public Criteria andCint2IsNull() {
            addCriterion("cint2 is null");
            return (Criteria) this;
        }

        public Criteria andCint2IsNotNull() {
            addCriterion("cint2 is not null");
            return (Criteria) this;
        }

        public Criteria andCint2EqualTo(Integer value) {
            addCriterion("cint2 =", value, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2NotEqualTo(Integer value) {
            addCriterion("cint2 <>", value, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2GreaterThan(Integer value) {
            addCriterion("cint2 >", value, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2GreaterThanOrEqualTo(Integer value) {
            addCriterion("cint2 >=", value, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2LessThan(Integer value) {
            addCriterion("cint2 <", value, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2LessThanOrEqualTo(Integer value) {
            addCriterion("cint2 <=", value, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2In(List<Integer> values) {
            addCriterion("cint2 in", values, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2NotIn(List<Integer> values) {
            addCriterion("cint2 not in", values, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2Between(Integer value1, Integer value2) {
            addCriterion("cint2 between", value1, value2, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint2NotBetween(Integer value1, Integer value2) {
            addCriterion("cint2 not between", value1, value2, "cint2");
            return (Criteria) this;
        }

        public Criteria andCint3IsNull() {
            addCriterion("cint3 is null");
            return (Criteria) this;
        }

        public Criteria andCint3IsNotNull() {
            addCriterion("cint3 is not null");
            return (Criteria) this;
        }

        public Criteria andCint3EqualTo(Integer value) {
            addCriterion("cint3 =", value, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3NotEqualTo(Integer value) {
            addCriterion("cint3 <>", value, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3GreaterThan(Integer value) {
            addCriterion("cint3 >", value, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3GreaterThanOrEqualTo(Integer value) {
            addCriterion("cint3 >=", value, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3LessThan(Integer value) {
            addCriterion("cint3 <", value, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3LessThanOrEqualTo(Integer value) {
            addCriterion("cint3 <=", value, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3In(List<Integer> values) {
            addCriterion("cint3 in", values, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3NotIn(List<Integer> values) {
            addCriterion("cint3 not in", values, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3Between(Integer value1, Integer value2) {
            addCriterion("cint3 between", value1, value2, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint3NotBetween(Integer value1, Integer value2) {
            addCriterion("cint3 not between", value1, value2, "cint3");
            return (Criteria) this;
        }

        public Criteria andCint4IsNull() {
            addCriterion("cint4 is null");
            return (Criteria) this;
        }

        public Criteria andCint4IsNotNull() {
            addCriterion("cint4 is not null");
            return (Criteria) this;
        }

        public Criteria andCint4EqualTo(Integer value) {
            addCriterion("cint4 =", value, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4NotEqualTo(Integer value) {
            addCriterion("cint4 <>", value, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4GreaterThan(Integer value) {
            addCriterion("cint4 >", value, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4GreaterThanOrEqualTo(Integer value) {
            addCriterion("cint4 >=", value, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4LessThan(Integer value) {
            addCriterion("cint4 <", value, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4LessThanOrEqualTo(Integer value) {
            addCriterion("cint4 <=", value, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4In(List<Integer> values) {
            addCriterion("cint4 in", values, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4NotIn(List<Integer> values) {
            addCriterion("cint4 not in", values, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4Between(Integer value1, Integer value2) {
            addCriterion("cint4 between", value1, value2, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint4NotBetween(Integer value1, Integer value2) {
            addCriterion("cint4 not between", value1, value2, "cint4");
            return (Criteria) this;
        }

        public Criteria andCint5IsNull() {
            addCriterion("cint5 is null");
            return (Criteria) this;
        }

        public Criteria andCint5IsNotNull() {
            addCriterion("cint5 is not null");
            return (Criteria) this;
        }

        public Criteria andCint5EqualTo(Integer value) {
            addCriterion("cint5 =", value, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5NotEqualTo(Integer value) {
            addCriterion("cint5 <>", value, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5GreaterThan(Integer value) {
            addCriterion("cint5 >", value, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5GreaterThanOrEqualTo(Integer value) {
            addCriterion("cint5 >=", value, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5LessThan(Integer value) {
            addCriterion("cint5 <", value, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5LessThanOrEqualTo(Integer value) {
            addCriterion("cint5 <=", value, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5In(List<Integer> values) {
            addCriterion("cint5 in", values, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5NotIn(List<Integer> values) {
            addCriterion("cint5 not in", values, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5Between(Integer value1, Integer value2) {
            addCriterion("cint5 between", value1, value2, "cint5");
            return (Criteria) this;
        }

        public Criteria andCint5NotBetween(Integer value1, Integer value2) {
            addCriterion("cint5 not between", value1, value2, "cint5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f1_w1_volume
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 19 16:01:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f1_w1_volume
     *
     * @mbggenerated Tue Jul 19 16:01:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}