package cn.com.jtang.po;

import java.io.Serializable;

public class Rule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.id
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.ruleorder
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    private String ruleorder;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.ruleorder
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    private String chineserule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.recordtypeid
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    private String recordtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.recordtypeid
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    private String tabletype;

    public String getTabletype() {
		return tabletype;
	}

	public void setTabletype(String tabletype) {
		this.tabletype = tabletype;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.id
     *
     * @return the value of rule.id
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    public String getId() {
        return id;
    }

    public String getChineserule() {
		return chineserule;
	}

	public void setChineserule(String chineserule) {
		this.chineserule = chineserule;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.id
     *
     * @param id the value for rule.id
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.ruleorder
     *
     * @return the value of rule.ruleorder
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    public String getRuleorder() {
        return ruleorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.ruleorder
     *
     * @param ruleorder the value for rule.ruleorder
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    public void setRuleorder(String ruleorder) {
        this.ruleorder = ruleorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.recordtypeid
     *
     * @return the value of rule.recordtypeid
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    public String getRecordtypeid() {
        return recordtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.recordtypeid
     *
     * @param recordtypeid the value for rule.recordtypeid
     *
     * @mbggenerated Wed Jul 06 16:57:59 CST 2016
     */
    public void setRecordtypeid(String recordtypeid) {
        this.recordtypeid = recordtypeid;
    }
}