package cn.com.jtang.po;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ServerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected int start = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected int limit = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public ServerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public void setStart(int start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public int getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public void setLimit(int limit) {
		this.limit = limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public int getLimit() {
		return limit;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andPortIsNull() {
			addCriterion("port is null");
			return (Criteria) this;
		}

		public Criteria andPortIsNotNull() {
			addCriterion("port is not null");
			return (Criteria) this;
		}

		public Criteria andPortEqualTo(String value) {
			addCriterion("port =", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotEqualTo(String value) {
			addCriterion("port <>", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThan(String value) {
			addCriterion("port >", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThanOrEqualTo(String value) {
			addCriterion("port >=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThan(String value) {
			addCriterion("port <", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThanOrEqualTo(String value) {
			addCriterion("port <=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLike(String value) {
			addCriterion("port like", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotLike(String value) {
			addCriterion("port not like", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortIn(List<String> values) {
			addCriterion("port in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotIn(List<String> values) {
			addCriterion("port not in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortBetween(String value1, String value2) {
			addCriterion("port between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotBetween(String value1, String value2) {
			addCriterion("port not between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andServerUsernameIsNull() {
			addCriterion("server_username is null");
			return (Criteria) this;
		}

		public Criteria andServerUsernameIsNotNull() {
			addCriterion("server_username is not null");
			return (Criteria) this;
		}

		public Criteria andServerUsernameEqualTo(String value) {
			addCriterion("server_username =", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameNotEqualTo(String value) {
			addCriterion("server_username <>", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameGreaterThan(String value) {
			addCriterion("server_username >", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("server_username >=", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameLessThan(String value) {
			addCriterion("server_username <", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameLessThanOrEqualTo(String value) {
			addCriterion("server_username <=", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameLike(String value) {
			addCriterion("server_username like", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameNotLike(String value) {
			addCriterion("server_username not like", value, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameIn(List<String> values) {
			addCriterion("server_username in", values, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameNotIn(List<String> values) {
			addCriterion("server_username not in", values, "serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameBetween(String value1, String value2) {
			addCriterion("server_username between", value1, value2,
					"serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerUsernameNotBetween(String value1, String value2) {
			addCriterion("server_username not between", value1, value2,
					"serverUsername");
			return (Criteria) this;
		}

		public Criteria andServerPwdIsNull() {
			addCriterion("server_pwd is null");
			return (Criteria) this;
		}

		public Criteria andServerPwdIsNotNull() {
			addCriterion("server_pwd is not null");
			return (Criteria) this;
		}

		public Criteria andServerPwdEqualTo(String value) {
			addCriterion("server_pwd =", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdNotEqualTo(String value) {
			addCriterion("server_pwd <>", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdGreaterThan(String value) {
			addCriterion("server_pwd >", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdGreaterThanOrEqualTo(String value) {
			addCriterion("server_pwd >=", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdLessThan(String value) {
			addCriterion("server_pwd <", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdLessThanOrEqualTo(String value) {
			addCriterion("server_pwd <=", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdLike(String value) {
			addCriterion("server_pwd like", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdNotLike(String value) {
			addCriterion("server_pwd not like", value, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdIn(List<String> values) {
			addCriterion("server_pwd in", values, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdNotIn(List<String> values) {
			addCriterion("server_pwd not in", values, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdBetween(String value1, String value2) {
			addCriterion("server_pwd between", value1, value2, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerPwdNotBetween(String value1, String value2) {
			addCriterion("server_pwd not between", value1, value2, "serverPwd");
			return (Criteria) this;
		}

		public Criteria andServerTypeIsNull() {
			addCriterion("server_type is null");
			return (Criteria) this;
		}

		public Criteria andServerTypeIsNotNull() {
			addCriterion("server_type is not null");
			return (Criteria) this;
		}

		public Criteria andServerTypeEqualTo(String value) {
			addCriterion("server_type =", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeNotEqualTo(String value) {
			addCriterion("server_type <>", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeGreaterThan(String value) {
			addCriterion("server_type >", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeGreaterThanOrEqualTo(String value) {
			addCriterion("server_type >=", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeLessThan(String value) {
			addCriterion("server_type <", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeLessThanOrEqualTo(String value) {
			addCriterion("server_type <=", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeLike(String value) {
			addCriterion("server_type like", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeNotLike(String value) {
			addCriterion("server_type not like", value, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeIn(List<String> values) {
			addCriterion("server_type in", values, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeNotIn(List<String> values) {
			addCriterion("server_type not in", values, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeBetween(String value1, String value2) {
			addCriterion("server_type between", value1, value2, "serverType");
			return (Criteria) this;
		}

		public Criteria andServerTypeNotBetween(String value1, String value2) {
			addCriterion("server_type not between", value1, value2,
					"serverType");
			return (Criteria) this;
		}

		public Criteria andEditTimeIsNull() {
			addCriterion("edit_time is null");
			return (Criteria) this;
		}

		public Criteria andEditTimeIsNotNull() {
			addCriterion("edit_time is not null");
			return (Criteria) this;
		}

		public Criteria andEditTimeEqualTo(Date value) {
			addCriterion("edit_time =", value, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeNotEqualTo(Date value) {
			addCriterion("edit_time <>", value, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeGreaterThan(Date value) {
			addCriterion("edit_time >", value, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("edit_time >=", value, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeLessThan(Date value) {
			addCriterion("edit_time <", value, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeLessThanOrEqualTo(Date value) {
			addCriterion("edit_time <=", value, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeIn(List<Date> values) {
			addCriterion("edit_time in", values, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeNotIn(List<Date> values) {
			addCriterion("edit_time not in", values, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeBetween(Date value1, Date value2) {
			addCriterion("edit_time between", value1, value2, "editTime");
			return (Criteria) this;
		}

		public Criteria andEditTimeNotBetween(Date value1, Date value2) {
			addCriterion("edit_time not between", value1, value2, "editTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server
	 * @mbggenerated  Fri Sep 23 14:33:36 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 23 09:52:34 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}