package cn.com.jtang.po;

import java.io.Serializable;
import java.util.Date;

public class Station implements Serializable {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
	private int id ;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public int getId() {
		return id;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
	public void setId(int id) {
		this.id = id;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.event
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operator
     *
     * @return the value of log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operator
     *
     * @param operator the value for log.operator
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.event
     *
     * @return the value of log.event
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public String getEvent() {
        return event;
    }

    public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.event
     *
     * @param event the value for log.event
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public void setEvent(String event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.createtime
     *
     * @return the value of log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.createtime
     *
     * @param createtime the value for log.createtime
     *
     * @mbggenerated Mon Aug 01 17:07:12 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}