package cn.com.jtang.po;

import java.util.ArrayList;
import java.util.List;

public class UserGroupAuthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public UserGroupAuthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUsergroupidIsNull() {
            addCriterion("usergroupid is null");
            return (Criteria) this;
        }

        public Criteria andUsergroupidIsNotNull() {
            addCriterion("usergroupid is not null");
            return (Criteria) this;
        }

        public Criteria andUsergroupidEqualTo(String value) {
            addCriterion("usergroupid =", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidNotEqualTo(String value) {
            addCriterion("usergroupid <>", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidGreaterThan(String value) {
            addCriterion("usergroupid >", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidGreaterThanOrEqualTo(String value) {
            addCriterion("usergroupid >=", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidLessThan(String value) {
            addCriterion("usergroupid <", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidLessThanOrEqualTo(String value) {
            addCriterion("usergroupid <=", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidLike(String value) {
            addCriterion("usergroupid like", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidNotLike(String value) {
            addCriterion("usergroupid not like", value, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidIn(List<String> values) {
            addCriterion("usergroupid in", values, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidNotIn(List<String> values) {
            addCriterion("usergroupid not in", values, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidBetween(String value1, String value2) {
            addCriterion("usergroupid between", value1, value2, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andUsergroupidNotBetween(String value1, String value2) {
            addCriterion("usergroupid not between", value1, value2, "usergroupid");
            return (Criteria) this;
        }

        public Criteria andAuthidIsNull() {
            addCriterion("authid is null");
            return (Criteria) this;
        }

        public Criteria andAuthidIsNotNull() {
            addCriterion("authid is not null");
            return (Criteria) this;
        }

        public Criteria andAuthidEqualTo(String value) {
            addCriterion("authid =", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidNotEqualTo(String value) {
            addCriterion("authid <>", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidGreaterThan(String value) {
            addCriterion("authid >", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidGreaterThanOrEqualTo(String value) {
            addCriterion("authid >=", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidLessThan(String value) {
            addCriterion("authid <", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidLessThanOrEqualTo(String value) {
            addCriterion("authid <=", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidLike(String value) {
            addCriterion("authid like", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidNotLike(String value) {
            addCriterion("authid not like", value, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidIn(List<String> values) {
            addCriterion("authid in", values, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidNotIn(List<String> values) {
            addCriterion("authid not in", values, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidBetween(String value1, String value2) {
            addCriterion("authid between", value1, value2, "authid");
            return (Criteria) this;
        }

        public Criteria andAuthidNotBetween(String value1, String value2) {
            addCriterion("authid not between", value1, value2, "authid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usergroupauth
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 01 17:23:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usergroupauth
     *
     * @mbggenerated Mon Aug 01 17:23:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}