package cn.com.jtang.po;

import java.io.Serializable;
import java.util.Date;

public class UserGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.id
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.groupname
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.createtime
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usergroup
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.id
     *
     * @return the value of usergroup.id
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.id
     *
     * @param id the value for usergroup.id
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.groupname
     *
     * @return the value of usergroup.groupname
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.groupname
     *
     * @param groupname the value for usergroup.groupname
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.createtime
     *
     * @return the value of usergroup.createtime
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.createtime
     *
     * @param createtime the value for usergroup.createtime
     *
     * @mbggenerated Mon Aug 01 17:41:42 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}